const fs = require("fs");
const path = require("path");
const { logWarn, logStep } = require("./logger");
const { toPackageName } = require("./utils");

const TEMPLATE_ROOT = path.resolve(__dirname, "..", "templates");
const DOCS_URL = "https://costrix.kaustubhvats.in";

function ensureDirForFile(filePath) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
}

function writeTextFileSafe(targetPath, content) {
  if (fs.existsSync(targetPath)) {
    return false;
  }

  ensureDirForFile(targetPath);
  fs.writeFileSync(targetPath, content, "utf8");
  return true;
}

function copyFileSafe(sourcePath, targetPath) {
  if (fs.existsSync(targetPath)) {
    return false;
  }

  ensureDirForFile(targetPath);
  fs.copyFileSync(sourcePath, targetPath);
  return true;
}

function renderFile(relativePath, sourceContent, appName) {
  if (relativePath === "package.json") {
    const parsed = JSON.parse(sourceContent);
    parsed.name = toPackageName(appName);
    return `${JSON.stringify(parsed, null, 2)}\n`;
  }

  return sourceContent;
}

function renderHelperReadme(appName) {
  return `# ${appName}

This project was generated by [Costrix](${DOCS_URL}).

## Costrix Docs

- Documentation: ${DOCS_URL}

## Quick Start

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`
2. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`
3. Open the app in your browser (URL shown in terminal).

## Available Scripts

- \`npm run dev\`: start webpack dev server for local development
- \`npm run test\`: run test suite with Jest
- \`npm run build\`: production build pipeline
- \`npm run prod\`: lint + typecheck + tests with coverage + production build

## Project Structure

\`\`\`text
public/      static assets (HTML + icons/images)
scripts/     build/dev helper scripts
src/         application source code
tests/       automated tests
\`\`\`

## Typical Workflow

1. Build features in \`src/\`
2. Add or update tests in \`tests/\`
3. Validate locally with:
   \`\`\`bash
   npm run test
   npm run prod
   \`\`\`

## Customization Notes

- Edit \`public/index.html\` for base HTML metadata.
- Update styling and UI starting from \`src/index.ts\` and \`src/App.module.css\`.
- Tweak build/tooling behavior via \`webpack.config.js\`, \`jest.config.cjs\`, and \`eslint.config.cjs\`.
`;
}

function copyTemplateDir(templateDir, projectDir, appName, rootTemplateDir) {
  const entries = fs.readdirSync(templateDir, { withFileTypes: true });

  entries.forEach((entry) => {
    const sourcePath = path.join(templateDir, entry.name);
    const relativePath = path.relative(rootTemplateDir, sourcePath);
    const normalizedRelativePath = relativePath.replace(/\\/g, "/");
    const outputRelativePath =
      normalizedRelativePath === "gitignore" ? ".gitignore" : normalizedRelativePath;
    const targetPath = path.join(projectDir, outputRelativePath);

    if (entry.isDirectory()) {
      fs.mkdirSync(targetPath, { recursive: true });
      copyTemplateDir(sourcePath, projectDir, appName, rootTemplateDir);
      return;
    }

    let created = false;
    if (normalizedRelativePath === "package.json") {
      const rawContent = fs.readFileSync(sourcePath, "utf8");
      const content = renderFile(normalizedRelativePath, rawContent, appName);
      created = writeTextFileSafe(targetPath, content);
    } else {
      created = copyFileSafe(sourcePath, targetPath);
    }

    if (created) {
      logStep(`Created ${outputRelativePath}`);
      return;
    }

    logWarn(`Skipped ${outputRelativePath} (already exists)`);
  });
}

function scaffoldProject(projectDir, appName) {
  fs.mkdirSync(projectDir, { recursive: true });
  copyTemplateDir(TEMPLATE_ROOT, projectDir, appName, TEMPLATE_ROOT);

  const readmePath = path.join(projectDir, "README.md");
  const readmeCreated = writeTextFileSafe(readmePath, renderHelperReadme(appName));
  if (readmeCreated) {
    logStep("Created README.md");
    return;
  }
  logWarn("Skipped README.md (already exists)");
}

module.exports = {
  scaffoldProject
};
